### PR TITLE
Corrections and improvements

### PR DESCRIPTION
**Pull request by triska**
This pull request corrects several memory leaks and simplifies the port to OpenSSL 1.1.0 with new compatibility macros and functions.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Oops, merged on github but as it doesn't compile anymore with openssl on Ubuntu I did a hard reset and push.  Now need to figure out what is wrong.

**Comment by triska** [comment]
I have tested this on Debian.

**Comment by JanWielemaker** [comment]
Well, it goes wrong on Ubuntu.  Guess a different version of OpenSSL (1.0.2g).  The definition is:

```
void X509_get0_signature(ASN1_BIT_STRING **psig, X509_ALGOR **palg,
                         const X509 *x);
```

That is why you must test features, not versions.  It is just too hard to get right.  Add a check for X509_get0_signature to `configure.in`.  Now you must guess/figure out which changes are connected to this.   Then just run ./build from the top dir to ensure the configuration is updated, configure is ran again and the library is rebuild.  __Be careful__ `./build` asks you to update packages/ssl.  Say __no__.

**Comment by triska** [comment]
I have added this now and re-filed as #54. Please test and merge as applicable.

Thank you!

**Pull request merged**
