### PR TITLE
ENHANCED: SSL: Enable DH key exchange. Many thanks to Charlie Hothers…

### PR DESCRIPTION
**Pull request by triska**
…all-Thomas for implementation advice.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
What does this do?  Should this be an option instead of being always enabled (if I read the source correctly?)

**Comment by triska** [comment]
This patch enables  [**Diffie–Hellman–Merkle key exchange**](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) for establishing secure connections.

I am supplying this patch to complement the already available ECDH ciphers, taking into account the [guide to deploying Diffie-Hellman for&nbsp;TLS](https://weakdh.org/sysadmin.html).

As discussed in #23, the patch makes several additional ciphers available when negotiating secure connections, most importantly:

<pre>
256 bits  DHE-RSA-AES256-SHA
256 bits  DHE-RSA-CAMELLIA256-SHA
128 bits  DHE-RSA-AES128-SHA
128 bits  DHE-RSA-SEED-SHA
128 bits  DHE-RSA-CAMELLIA128-SHA
</pre>

You can use `sslscan host:port | grep -i acc` to see the ciphers that your TLS server accepts.

I have followed the advice given in the [openssl documentation](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_tmp_dh_callback.html):

> Applications should therefore generate their own DH parameters during the installation process using the **`openssl dhparam`** application. This application guarantees that "strong" primes are used.

It is infeasible to generate these parameters on the fly, so they are embedded in the source code. This is perfectly OK, since these parameters *must* be public due to the way the protocol works. You can generate different parameters yourself and replace the existing ones any time.

Important additional points are mentioned in [Imperfect Forward Secrecy: How Diffie-Hellman Fails in Practice](https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf). 

Note that users can easily choose among the available ciphers using the `cipher_list/1` option, available as `--cipherlist` in the HTTP Unix daemon. For example, to disable the DH ciphers that this patch makes available, use `--cipherlist='DEFAULT:!DH'`.

**Comment by FunctionAnalysis** [comment]
Elliptic curves are well known not to be post-quantum secure.

**Comment by triska** [comment]
@FunctionAnalysis: Your comment is obvious for experts in this area, but I still want to point out explicitly that this is a point in favour of this patch, not against it: It makes DH available without relying on elliptic curves, but on the multiplicative group of integers modulo&nbsp;p.

The ECDH ciphers are already available due to a previous patch, and can of course also be disabled using the `--cipherlist` option.

**Comment by JanWielemaker** [comment]
Ok.  Thanks.  Merged.

**Pull request merged**
