### PR TITLE
Corrections and improvements

### PR DESCRIPTION
**Pull request by triska**
This corrects several memory leaks and uses compatibility macros to simplify porting.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
If I change around line 767 to this, i.e., dropping `const`, it compiles and passes the checks.  That looks ok with me.  Add and merge?

```
  ASN1_BIT_STRING *psig;
  X509_ALGOR *palg;

  X509_get0_signature(&psig, &palg, data);
```

**Comment by triska** [comment]
The problem with dropping the const is that it won't compile with OpenSSL 1.1.0. Please use an explicit cast if in doubt, and try it also with OpenSSL&nbsp;1.1.0.

I am also doing this in: 

    i2a_ASN1_INTEGER(mem, (ASN1_BIT_STRING *) psig);

I have no idea why this argument isn't declared `const` in OpenSSL, but an explicit cast seemed to be the only way out to reuse the code in both OpenSSL 1.1.0 and prior versions.

**Comment by triska** [comment]
I have tracked down the reason for this: In OpenSSL prior to 1.1.0, the function `X509_get0_signature` ships with some versions (1.0.2j being an example), with the following prototype:

<pre>
void X509_get0_signature(ASN1_BIT_STRING **psig, X509_ALGOR **palg,
                         const X509 *x);
</pre>

However, starting with OpenSSL 1.1.0, the prototype has changed to:

<pre>
void X509_get0_signature(<b>const</b> ASN1_BIT_STRING **psig,
                         <b>const</b> X509_ALGOR **palg, const X509 *x);
</pre>

Please solve this as you consider best.

**Comment by JanWielemaker** [comment]
Should now be working.   These type of API changes are really annoying :(  Configures, compiles and checks clean on Fedora (openssl 1.0.2j)

**Comment by triska** [comment]
Awesome work, thank you!

It only fails on all OpenSSL versions different from 1.0.2.

I have created #55 to correct this.

**Comment by JanWielemaker** [comment]
Thanks.

**Pull request merged**
