### PR TITLE
PORT: RTools42, link order for OS libs, add libz

### PR DESCRIPTION
**Pull request by mgondan**

### CODE REVIEW

**Comment by mgondan** [comment]
Please consider (especially the modification on line 21)

**Comment by JanWielemaker** [comment]
Oops, slipped.   Sorry.  I think I'm ok with the change around line 21.    I can't place the early one though.   What is z.lib anyway?   I doesn't seem to be needed and I can't even find it on my machine.

**Comment by mgondan** [comment]
IIRC I needed to link with libz.a, as well. For cmake (?) or whatever program is in charge, z.lib = libz.a = -lz.

**Comment by JanWielemaker** [comment]
I doubt that.  the zip library is called zlib1.{lib,dll}.   CMake is not going to find that from z.lib (I hope).  Something weird is going on.  Either something RTools specific or something intermittent that is not really needed.    Before accepting that must get clear.  I'm happy to merge the second step if you want me to.   That might be needed for static linking,  For dynamic linking it should not make a difference.

**Comment by mgondan** [comment]
I have looked at this again (RTools42):

This made it work without extra command line arguments to cmake. Please note the semicolon.

if(NOT OPENSSL_OS_LIBS)
  if(WIN32)
    set(OPENSSL_OS_LIBS ws2_32.lib;crypt32.lib;crypto.lib;z.lib)
  else()
    set(OPENSSL_OS_LIBS)
  endif()
endif()

Actually, there are no files with extension ".lib" in MinGW, so at some point, z.lib is mapped to libz.a (which is indeed found at /x86_64-w64-mingw32.static.posix/lib/).

**Comment by JanWielemaker** [comment]
I don't understand why, but the original patch doesn't seem to affect the normal build, so I've applied it.   Github doesn't pick up this fact if you do the rebase locally :cry:   

Note that ; and space have for the most part the same meaning in CMake.    ; is the list separator.

**Pull request closed without merging**
